### ISSUE TITLE
Feed view in "start from beginning" mode does not always include all lower items

### ISSUE THREAD

**Issue by taylorhadden** [suchnsuch/tangent-public#5]
Reported by Dor.

Swapping into “Beginning” from “end” can result in a state where items are not added to the bottom on scroll.

Swapping ascending/descending and back appears to make the problem go away, but I think it’s more to do with how the “current” node is being retained?

**Comment by taylorhadden** [comment]
This was actually caused by the "load" event being lost on first load when a file's contents were still cached and immediately available.

**Comment by taylorhadden** [comment]
This is in theory fixed in v0.3.4-beta.1. Waiting on user confirmation.

**Comment by akadormouse** [comment]
Seems to be working for me now. Though I may have missed something since I dont use it often.

**Comment by taylorhadden** [comment]
Marking this as closed. If the issue crops up again, it can be reopened.
